apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prober-backend.fullname" . }}-config
  labels:
    {{- include "prober-backend.labels" . | nindent 4 }}
stringData:
  config.yml: |
    {{- include "prober-backend.renderedConfig" . | nindent 4 }}
