{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prober-agent.fullname" . }}-config
  labels:
    {{- include "prober-agent.labels" . | nindent 4 }}
stringData:
  config.yml: |
    {{- include "prober-agent.renderedConfig" . | nindent 4 }}
{{- end }}
